/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary-fixed": "#001b3d",
        "tertiary-fixed": "#ffdeac",
        "background": "#f8f9fa",
        "on-secondary-container": "#495b81",
        "on-primary-fixed-variant": "#244779",
        "on-error-container": "#93000a",
        "surface-container-low": "#f3f4f5",
        "surface-container": "#edeeef",
        "on-surface": "#191c1d",
        "on-secondary-fixed": "#051b3c",
        "on-tertiary-fixed-variant": "#604100",
        "surface-variant": "#e1e3e4",
        "primary-fixed": "#d6e3ff",
        "primary-container": "#002d5e",
        "primary-fixed-dim": "#a9c7ff",
        "outline": "#747780",
        "on-tertiary-fixed": "#281900",
        "outline-variant": "#c3c6d0",
        "error": "#ba1a1a",
        "on-secondary-fixed-variant": "#34476a",
        "surface": "#f8f9fa",
        "on-primary-container": "#7696cd",
        "surface-container-highest": "#e1e3e4",
        "secondary": "#4c5e84",
        "secondary-fixed-dim": "#b4c6f1",
        "inverse-primary": "#a9c7ff",
        "on-surface-variant": "#43474f",
        "tertiary-container": "#402a00",
        "surface-bright": "#f8f9fa",
        "surface-dim": "#d9dadb",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#c68a00",
        "on-primary": "#ffffff",
        "on-background": "#191c1d",
        "surface-container-high": "#e7e8e9",
        "tertiary": "#251700",
        "inverse-surface": "#2e3132",
        "on-secondary": "#ffffff",
        "primary": "#001939",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "secondary-container": "#c2d4ff",
        "surface-tint": "#3e5f92",
        "surface-container-lowest": "#ffffff",
        "inverse-on-surface": "#f0f1f2",
        "tertiary-fixed-dim": "#ffba38",
        "secondary-fixed": "#d8e2ff"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"],
        "mono": ["JetBrains Mono", "monospace"]
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      animation: {
        'spin-slow': 'spin 3.5s linear infinite',
        'spin-medium': 'spin 2s linear infinite',
      },
    },
  },
  plugins: [],
}
